version: "3.2"

services:
  postgres:
    container_name: slavim-postgres
    image: postgres:12-alpine
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=slavim-pass
      - POSTGRES_USER=slavim-user
      - POSTGRES_DB=slavim-db
  redis:
    container_name: slavim-redis
    image: "redis:6.2.6"
    ports:
      - "6379:6379"
  cassandra:
    container_name: slavim-cassandra
    image: "cassandra:3.11.12"
    ports:
      - "9042:9042"
    volumes:
      - "./cassandra_init/cassandra_init.sh:/cassandra_init.sh"
    command: "sh /cassandra_init.sh"
  rabbitmq-stomp:
    container_name: slavim-rabbitmq-stomp
    image: "jorgeacetozi/rabbitmq-stomp:3.6"
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"

volumes:
  cassandra-data: {}